from typing import TypedDict, List, Dict, Any


class BrainState(TypedDict):

    # Original document text
    raw_text: str

    # Generated chunks
    chunks: List[str]

    # Retrieved chunks during QA
    retrieved_chunks: List[str]

    # Structured rules extracted by L1
    extracted_rules: List[Dict[str, Any]]

    # SOP generated by L3
    structured_sop: str

    # Contradictions found by L5
    contradictions: List[Dict[str, Any]]

    # Detailed contradiction report
    contradiction_report: List[Dict[str, Any]]

    # Hallucination report from L4
    hallucination_report: List[Dict[str, Any]]

    # Hallucination score from L4
    hallucination_score: float

    # Final confidence score from L6
    confidence_score: float

    # Final routing decision
    review_status: str

    # Audit trail
    agent_logs: List[str]